# Generated by Django 5.1.1 on 2026-09-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0007_rename_hopdong_phanbochitieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='phanbochitieu',
            name='nhom_hd',
            field=models.IntegerField(default=1, verbose_name='Nhóm hợp đồng'),
        ),
    ]
