# Generated by Django 5.1.1 on 2026-09-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0013_phanbochitieu_cbda_quan_ly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phancongtre',
            name='cbda_quan_ly',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBDA quản lý'),
        ),
        migrations.AddField(
            model_name='phancongtre',
            name='nhom_hd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phan_cong_tre', to='quanly.nhomhd', verbose_name='Nhóm hợp đồng'),
        ),
        migrations.AlterField(
            model_name='phancongtre',
            name='phan_bo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='danh_sach_phan_cong', to='quanly.phanbochitieu', verbose_name='Phân bổ chỉ tiêu'),
        ),
    ]
