# Generated by Django 5.1.1 on 2026-09-14 11:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0005_alter_hopdong_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='can_bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.canbo', verbose_name='Cán bộ can thiệp'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='dinh_muc_di_lai_cs',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=12, verbose_name='Định mức đi lại CSXH'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='dinh_muc_di_lai_phcn',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=12, verbose_name='Định mức đi lại PHCN'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='gia_tri_hd_du_kien',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(choices=[('DE_XUAT', 'Chờ đề xuất HĐ'), ('DA_TAO', 'Đã tạo Hợp đồng')], default='DE_XUAT', max_length=20, verbose_name='Trạng thái HĐ'),
        ),
    ]
