# Generated by Django 5.1.1 on 2026-09-16 10:52

from django.db import migrations, models


def copy_assignment_period(apps, schema_editor):
    Journal = apps.get_model("quanly", "NhatKyThucHien")
    Assignment = apps.get_model("quanly", "PhanCongTre")
    assignment_periods = dict(Assignment.objects.values_list("id", "ky_phan_cong"))
    for journal in Journal.objects.all().iterator():
        journal.ky_can_thiep = assignment_periods.get(journal.phan_cong_id, 1) or 1
        journal.save(update_fields=["ky_can_thiep"])


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0016_nhatkythuchien_gio_bat_dau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkythuchien',
            name='ky_can_thiep',
            field=models.PositiveIntegerField(default=1, verbose_name='Kỳ can thiệp'),
        ),
        migrations.RunPython(copy_assignment_period, migrations.RunPython.noop),
    ]
