# Generated by Django 5.1.1 on 2026-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0031_gia_han_hop_dong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nghiemthu',
            name='ket_qua',
            field=models.CharField(choices=[('DAT', 'Đạt'), ('KHONG_DAT', 'Không đạt')], default='DAT', max_length=30, verbose_name='Kết quả'),
        ),
    ]
