# Generated by Django 5.1.1 on 2026-09-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0006_alter_hopdong_can_bo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HopDong',
            new_name='PhanBoChiTieu',
        ),
    ]
