# Generated by Django 5.1.1 on 2026-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0008_phanbochitieu_nhom_hd'),
    ]

    operations = [
        migrations.AddField(
            model_name='phanbochitieu',
            name='tham_gia_ct',
            field=models.BooleanField(default=True, verbose_name='Tham gia can thiệp'),
        ),
        migrations.AlterField(
            model_name='phanbochitieu',
            name='so_buoi_cs',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='phanbochitieu',
            name='so_buoi_phcn',
            field=models.IntegerField(default=20),
        ),
    ]
