# Generated by Django 5.1.1 on 2026-09-14 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_remove_hopdong_gia_tri_hop_dong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='dinh_muc_di_lai_cs',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=12, verbose_name='Định mức đi lại CSXH'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='dinh_muc_di_lai_phcn',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=12, verbose_name='Định mức đi lại PHCN'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='gia_tri_hd_du_kien',
            field=models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=15),
        ),
    ]
