# Generated by Django 5.1.1 on 2026-09-14 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='den_ngay',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='loai_hop_dong',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='ngay_ky',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='nhom_hd',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='tu_ngay',
        ),
        migrations.AddField(
            model_name='hopdong',
            name='ngay_lap_de_xuat',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày lập đề xuất'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='so_buoi_cs',
            field=models.PositiveIntegerField(default=0, verbose_name='Số buổi dự kiến/trẻ (CSXH)'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='so_buoi_phcn',
            field=models.PositiveIntegerField(default=0, verbose_name='Số buổi dự kiến/trẻ (PHCN)'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='so_thang_thuc_hien',
            field=models.PositiveIntegerField(default=1, verbose_name='Số tháng thực hiện'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='so_tre_cs',
            field=models.PositiveIntegerField(default=0, verbose_name='Số trẻ CSXH'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='so_tre_phcn',
            field=models.PositiveIntegerField(default=0, verbose_name='Số trẻ PHCN'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='can_bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.canbo', verbose_name='Cán bộ chuyên trách'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='gia_tri_hop_dong',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Tổng giá trị dự kiến (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='so_hop_dong',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số hợp đồng'),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(choices=[('DE_XUAT', 'Đề xuất ký'), ('DA_DUYET', 'Đã duyệt'), ('DA_KY', 'Đã ký Hợp đồng'), ('HUY', 'Đã hủy')], default='DE_XUAT', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
