# Generated by Django 5.1.1 on 2026-09-28 16:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0032_alter_nghiemthu_ket_qua'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHinhThue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('tu_ngay', models.DateField(unique=True, verbose_name='Hiệu lực từ ngày')),
                ('nguong_thue', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Ngưỡng thuế')),
                ('ty_le', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Tỷ lệ thuế')),
                ('can_cu_phap_ly', models.TextField(verbose_name='Căn cứ pháp lý')),
            ],
            options={
                'ordering': ['-tu_ngay', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhieuThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ky_can_thiep', models.PositiveIntegerField(verbose_name='Kỳ can thiệp')),
                ('lan_thanh_toan', models.PositiveIntegerField(verbose_name='Lần thanh toán')),
                ('tong_tien_cong', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('tong_tien_di_lai', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('thue_tncn', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('thuc_nhan', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('nguong_thue', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('ty_le_thue', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8)),
                ('trang_thai', models.CharField(choices=[('CHO_CHI', 'Chờ chi'), ('DA_CHI', 'Đã chi'), ('HUY', 'Hủy')], default='CHO_CHI', max_length=20)),
                ('ngay_lap', models.DateField(default=django.utils.timezone.localdate)),
                ('ngay_chi', models.DateField(blank=True, null=True)),
                ('ly_do_huy', models.TextField(blank=True, default='')),
                ('ngay_huy', models.DateField(blank=True, null=True)),
                ('hoat_dong', models.BooleanField(default=True, null=True)),
                ('ghi_chu', models.TextField(blank=True, default='')),
                ('can_bo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thanh_toan', to='quanly.canbo', verbose_name='CBCT')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thanh_toan', to='quanly.hopdong', verbose_name='Hợp đồng')),
                ('huy_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thanh_toan_huy', to=settings.AUTH_USER_MODEL)),
                ('lap_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thanh_toan_lap', to=settings.AUTH_USER_MODEL)),
                ('xac_nhan_chi_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thanh_toan_xac_nhan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_lap', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('hoat_dong', models.BooleanField(default=True, null=True)),
                ('so_buoi', models.PositiveIntegerField(default=0)),
                ('so_luot_di_lai_cbct', models.PositiveIntegerField(default=0)),
                ('don_gia_cong', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('dinh_muc_di_lai', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('tien_cong', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('tien_di_lai', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18)),
                ('ghi_chu', models.TextField(blank=True, default='')),
                ('nhat_ky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_phieu_thanh_toan', to='quanly.nhatkythuchien', verbose_name='Nhật ký')),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet', to='quanly.phieuthanhtoan', verbose_name='Phiếu thanh toán')),
            ],
        ),
        migrations.AddConstraint(
            model_name='phieuthanhtoan',
            constraint=models.UniqueConstraint(fields=('can_bo', 'hop_dong', 'ky_can_thiep', 'hoat_dong'), name='uq_phieu_cb_hd_ky_active'),
        ),
        migrations.AddConstraint(
            model_name='phieuthanhtoan',
            constraint=models.UniqueConstraint(fields=('can_bo', 'hop_dong', 'lan_thanh_toan', 'hoat_dong'), name='uq_phieu_cb_hd_lan_active'),
        ),
        migrations.AddConstraint(
            model_name='phieuthanhtoan',
            constraint=models.CheckConstraint(condition=models.Q(('ky_can_thiep__gte', 1), ('ky_can_thiep__lte', 30)), name='ck_phieu_ky_range'),
        ),
        migrations.AddConstraint(
            model_name='phieuthanhtoan',
            constraint=models.CheckConstraint(condition=models.Q(('lan_thanh_toan__gte', 1)), name='ck_phieu_lan_gt0'),
        ),
        migrations.AddConstraint(
            model_name='phieuthanhtoan',
            constraint=models.CheckConstraint(condition=models.Q(('tong_tien_cong__gte', 0), ('tong_tien_di_lai__gte', 0), ('thue_tncn__gte', 0), ('thuc_nhan__gte', 0)), name='ck_phieu_amounts_gte0'),
        ),
        migrations.AddConstraint(
            model_name='chitietphieuthanhtoan',
            constraint=models.UniqueConstraint(fields=('nhat_ky', 'hoat_dong'), name='uq_ct_phieu_nhat_ky_active'),
        ),
        migrations.AddConstraint(
            model_name='chitietphieuthanhtoan',
            constraint=models.CheckConstraint(condition=models.Q(('tien_cong__gte', 0), ('tien_di_lai__gte', 0)), name='ck_ct_phieu_amounts_gte0'),
        ),
    ]
