# Generated by Django 5.1.1 on 2026-09-16 10:28

from django.db import migrations, models


def copy_legacy_travel_to_cbct(apps, schema_editor):
    Journal = apps.get_model("quanly", "NhatKyThucHien")
    for journal in Journal.objects.all().iterator():
        journal.so_luot_di_lai_cbct = journal.so_luot_di_lai
        journal.save(update_fields=["so_luot_di_lai_cbct"])


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0015_recalculate_journal_travel_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkythuchien',
            name='gio_bat_dau',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu'),
        ),
        migrations.AddField(
            model_name='nhatkythuchien',
            name='gio_ket_thuc',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc'),
        ),
        migrations.AddField(
            model_name='nhatkythuchien',
            name='so_luot_di_lai_cbct',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượt đi lại CBCT'),
        ),
        migrations.AddField(
            model_name='tre',
            name='ace_ruot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ACE ruột'),
        ),
        migrations.AlterField(
            model_name='nhatkythuchien',
            name='so_luot_di_lai',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượt đi lại PH'),
        ),
        migrations.AddConstraint(
            model_name='nhatkythuchien',
            constraint=models.CheckConstraint(condition=models.Q(('so_luot_di_lai_cbct__gte', 0)), name='ck_nk_di_lai_cbct_gte0'),
        ),
        migrations.RunPython(copy_legacy_travel_to_cbct, migrations.RunPython.noop),
    ]
