# Generated by Django 5.1.1 on 2026-09-06 14:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_don_vi', models.CharField(max_length=20, unique=True, verbose_name='Mã Đơn Vị')),
                ('ten_don_vi', models.CharField(max_length=200, verbose_name='Tên Đơn Vị')),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('mstdv', models.CharField(max_length=20, unique=True, verbose_name='Mã số thuế')),
                ('nguoi_dai_dien', models.CharField(max_length=100, verbose_name='Người đại diện')),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='NhomHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom_hd', models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm hợp đồng')),
                ('ten_nhom_hd', models.CharField(max_length=200, verbose_name='Tên nhóm hợp đồng')),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tinh', models.CharField(max_length=20, unique=True, verbose_name='Mã Tỉnh')),
                ('ten_tinh', models.CharField(max_length=100, verbose_name='Tên Tỉnh/Thành phố')),
            ],
        ),
        migrations.CreateModel(
            name='CanBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_can_bo', models.CharField(max_length=20, unique=True, verbose_name='Mã CBCT')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('cccd', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số CCCD')),
                ('mst', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã số thuế')),
                ('gioi_tinh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Giới tính')),
                ('ngay_cap', models.DateField(blank=True, null=True, verbose_name='Ngày cấp CCCD')),
                ('noi_cap', models.CharField(max_length=200, verbose_name='Nơi cấp')),
                ('tai_khoan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tài khoản')),
                ('ngan_hang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngân hàng')),
                ('chi_nhanh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chi nhánh')),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.donvi', verbose_name='Đơn vị trực thuộc')),
                ('tinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.tinh', verbose_name='Tỉnh/Thành phố')),
            ],
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hop_dong', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('loai_hop_dong', models.CharField(choices=[('HĐDV', 'Hợp đồng dịch vụ'), ('HĐTV', 'Hợp đồng tư vấn')], default='HĐDV', max_length=10, verbose_name='Loại hợp đồng')),
                ('ngay_ky', models.DateField(verbose_name='Ngày ký')),
                ('tu_ngay', models.DateField(verbose_name='Từ ngày')),
                ('den_ngay', models.DateField(verbose_name='Đến ngày')),
                ('gia_tri_hop_dong', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Giá trị hợp đồng (VNĐ)')),
                ('trang_thai', models.CharField(choices=[('dang_chay', 'Đang chạy'), ('sap_het_han', 'Còn < 30 ngày'), ('da_het_han', 'Đã hết hạn'), ('da_thanh_ly', 'Đã thanh lý')], default='dang_chay', max_length=20, verbose_name='Trạng thái')),
                ('can_bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.canbo', verbose_name='Cán bộ can thiệp')),
                ('nhom_hd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.nhomhd', verbose_name='Nhóm hợp đồng')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTieuHopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tre_phcn', models.PositiveIntegerField(default=0, verbose_name='Số trẻ PHCN')),
                ('so_buoi_phcn', models.PositiveIntegerField(default=20, verbose_name='Số buổi/trẻ PHCN mặc định')),
                ('so_tre_cs', models.PositiveIntegerField(default=0, verbose_name='Số trẻ Chăm sóc')),
                ('so_buoi_cs', models.PositiveIntegerField(default=10, verbose_name='Số buổi/trẻ CS mặc định')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('can_bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.canbo', verbose_name='Cán bộ can thiệp')),
                ('nhom_hd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.nhomhd', verbose_name='Nhóm hợp đồng')),
            ],
        ),
        migrations.CreateModel(
            name='Tre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tre', models.CharField(max_length=20, unique=True, verbose_name='Mã trẻ')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('ma_tinh', models.CharField(max_length=10, verbose_name='Mã tỉnh')),
                ('ten_phu_huynh', models.CharField(max_length=100, verbose_name='Tên phụ huynh')),
                ('dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Điện thoại')),
                ('ten_tai_khoan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên tài khoản')),
                ('tai_khoan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tài khoản')),
                ('ngan_hang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngân hàng')),
                ('chi_nhanh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chi nhánh')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('tinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.tinh', verbose_name='Tỉnh/Thành phố')),
            ],
        ),
        migrations.CreateModel(
            name='PhanCongTre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_dich_vu', models.CharField(choices=[('VLTL', 'Vật lý trị liệu'), ('HDTL', 'Hoạt động trị liệu'), ('NNTL', 'Ngôn ngữ trị liệu'), ('GDDB', 'Giáo dục đặc biệt'), ('CSXH', 'Chăm sóc xã hội'), ('CSYT', 'Chăm sóc y tế')], max_length=10, verbose_name='Loại dịch vụ')),
                ('so_buoi_du_kien', models.PositiveIntegerField(default=20, verbose_name='Số buổi dự kiến')),
                ('dinh_muc_di_lai', models.DecimalField(decimal_places=0, default=Decimal('50000'), max_digits=10, verbose_name='Định mức đi lại (VNĐ)')),
                ('dia_diem_ct', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm can thiệp')),
                ('hinh_thuc_ct', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hình thức can thiệp')),
                ('dot_phan_cong', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đợt phân công')),
                ('ky_phan_cong', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kỳ phân công')),
                ('ngay_phan_cong', models.DateField(blank=True, null=True, verbose_name='Ngày phân công')),
                ('trang_thai', models.CharField(choices=[('dang_can_thiệp', 'Đang can thiệp'), ('da_hoan_thanh', 'Đã hoàn thành'), ('khong_can_thiệp', 'Không can thiệp')], default='dang_can_thiệp', max_length=20, verbose_name='Trạng thái trẻ')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_phan_cong', to='quanly.hopdong', verbose_name='Hợp đồng')),
                ('tre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.tre', verbose_name='Trẻ')),
            ],
        ),
        migrations.CreateModel(
            name='Xa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_xa', models.CharField(max_length=20, unique=True, verbose_name='Mã Xã')),
                ('ten_xa', models.CharField(max_length=100, verbose_name='Tên Xã/Phường')),
                ('tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.tinh', verbose_name='Thuộc Tỉnh')),
            ],
        ),
        migrations.AddField(
            model_name='tre',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.xa', verbose_name='Xã/Phường'),
        ),
        migrations.AddField(
            model_name='canbo',
            name='xa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.xa', verbose_name='Xã/Phường'),
        ),
    ]
