# Generated by Django 5.1.1 on 2026-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_alter_hopdong_dinh_muc_di_lai_cs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(choices=[('DE_XUAT', 'Chờ đề xuất HĐ'), ('DA_TAO', 'Đã tạo Hợp đồng')], default='NHAP', max_length=20),
        ),
    ]
