# Generated by Django 5.1.1 on 2026-09-16 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0011_dotthanhtoandilaiphuhuynh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canbo',
            options={'ordering': ['ho_ten'], 'verbose_name': 'Cán bộ can thiệp', 'verbose_name_plural': 'Cán bộ can thiệp'},
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='can_bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hop_dong', to='quanly.canbo', verbose_name='Cán bộ can thiệp'),
        ),
        migrations.AlterField(
            model_name='phanbochitieu',
            name='can_bo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phan_bo_chi_tieu', to='quanly.canbo', verbose_name='Cán bộ can thiệp'),
        ),
        migrations.CreateModel(
            name='LichSuDieuChuyenPhanCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('nguoi_thuc_hien', models.CharField(blank=True, max_length=150, null=True)),
                ('ly_do', models.TextField(blank=True, null=True)),
                ('phan_bo_cu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_su_phan_cong_cu', to='quanly.phanbochitieu')),
                ('phan_bo_moi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lich_su_phan_cong_moi', to='quanly.phanbochitieu')),
                ('phan_cong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_dieu_chuyen', to='quanly.phancongtre')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
