# Generated by Django 5.1.1 on 2026-09-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0012_alter_canbo_options_alter_hopdong_can_bo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phanbochitieu',
            name='cbda_quan_ly',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBDA quản lý'),
        ),
        migrations.AlterField(
            model_name='phanbochitieu',
            name='can_bo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phan_bo_chi_tieu', to='quanly.canbo', verbose_name='Cán bộ can thiệp'),
        ),
    ]
