# Generated by Django 5.1.1 on 2026-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0017_nhatkythuchien_ky_can_thiep'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatkythuchien',
            name='lan_thanh_toan',
            field=models.PositiveIntegerField(default=1, verbose_name='Lần thanh toán'),
        ),
    ]
