# Generated by Django 5.1.1 on 2026-09-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_remove_hopdong_den_ngay_remove_hopdong_loai_hop_dong_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='gia_tri_hop_dong',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='so_thang_thuc_hien',
        ),
        migrations.AddField(
            model_name='hopdong',
            name='den_ngay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='dinh_muc_di_lai_cs',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Định mức đi lại CSXH'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='dinh_muc_di_lai_phcn',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Định mức đi lại PHCN'),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='gia_tri_hd_du_kien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='ngay_ky',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopdong',
            name='tu_ngay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='so_buoi_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='so_buoi_phcn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='so_hop_dong',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='so_tre_cs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='so_tre_phcn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hopdong',
            name='trang_thai',
            field=models.CharField(choices=[('NHAP', 'Nháp phân bổ'), ('DE_XUAT', 'Chờ đề xuất HĐ'), ('DA_TAO', 'Đã tạo Hợp đồng')], default='NHAP', max_length=20),
        ),
    ]
