# Generated by Django 5.1.1 on 2026-09-16 02:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0010_domain_model_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotThanhToanDiLaiPhuHuynh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('nam', models.PositiveIntegerField(verbose_name='Năm')),
                ('thang', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('ngay_de_nghi', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đề nghị')),
                ('trang_thai', models.CharField(default='CHO_THANH_TOAN', max_length=30, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dot_thanh_toan_phu_huynh', to='quanly.hopdong', verbose_name='Hợp đồng')),
            ],
            options={
                'ordering': ['-nam', '-thang', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietThanhToanDiLaiPhuHuynh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('so_luot_di_lai', models.PositiveIntegerField(default=0, verbose_name='Số lượt đi lại thanh toán')),
                ('dinh_muc_di_lai', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Định mức đi lại')),
                ('thanh_tien', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='Thành tiền')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('nhat_ky', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet_di_lai_phu_huynh', to='quanly.nhatkythuchien', verbose_name='Nhật ký thực hiện')),
                ('dot_thanh_toan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chi_tiet', to='quanly.dotthanhtoandilaiphuhuynh', verbose_name='Đợt thanh toán')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dotthanhtoandilaiphuhuynh',
            constraint=models.UniqueConstraint(fields=('hop_dong', 'nam', 'thang'), name='uq_dottt_phuhuynh_hd_nam_thang'),
        ),
        migrations.AddConstraint(
            model_name='dotthanhtoandilaiphuhuynh',
            constraint=models.CheckConstraint(condition=models.Q(('thang__gte', 1), ('thang__lte', 12)), name='ck_dottt_phuhuynh_thang'),
        ),
        migrations.AddConstraint(
            model_name='chitietthanhtoandilaiphuhuynh',
            constraint=models.UniqueConstraint(fields=('dot_thanh_toan', 'nhat_ky'), name='uq_cttt_phuhuynh_dot_nhatky'),
        ),
        migrations.AddConstraint(
            model_name='chitietthanhtoandilaiphuhuynh',
            constraint=models.CheckConstraint(condition=models.Q(('so_luot_di_lai__gte', 0)), name='ck_cttt_phuhuynh_luot_gte0'),
        ),
    ]
