from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from quanly import views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(template_name="quanly/login.html"), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
    path("", login_required(views.trang_chu), name="trang_chu"),
    path("admin/", admin.site.urls),

    path("don-vi/", login_required(views.danh_sach_don_vi), name="danh_sach_don_vi"),
    path("don-vi/them/", login_required(views.them_don_vi), name="them_don_vi"),
    path("don-vi/sua/<int:id>/", login_required(views.sua_don_vi), name="sua_don_vi"),
    path("don-vi/xoa/<int:id>/", login_required(views.xoa_don_vi), name="xoa_don_vi"),
    path("don-vi/import/", login_required(views.import_don_vi), name="import_don_vi"),

    path("tre/", login_required(views.danh_sach_tre), name="danh_sach_tre"),
    path("tre/them/", login_required(views.them_tre), name="them_tre"),
    path("tre/sua/<int:id>/", login_required(views.sua_tre), name="sua_tre"),
    path("tre/xoa/<int:id>/", login_required(views.xoa_tre), name="xoa_tre"),
    path("tre/import/", login_required(views.import_tre), name="import_tre"),

    path("can-bo/", login_required(views.danh_sach_can_bo), name="danh_sach_can_bo"),
    path("can-bo/them/", login_required(views.them_can_bo), name="them_can_bo"),
    path("can-bo/sua/<int:id>/", login_required(views.sua_can_bo), name="sua_can_bo"),
    path("can-bo/xoa/<int:id>/", login_required(views.xoa_can_bo), name="xoa_can_bo"),
    path("can-bo/import/", login_required(views.import_can_bo), name="import_can_bo"),

    path("nhom-hd/", login_required(views.danh_sach_nhom_hd), name="danh_sach_nhom_hd"),
    path("nhom-hd/them/", login_required(views.them_nhom_hd), name="them_nhom_hd"),
    path("nhom-hd/sua/<int:id>/", login_required(views.sua_nhom_hd), name="sua_nhom_hd"),
    path("nhom-hd/xoa/<int:id>/", login_required(views.xoa_nhom_hd), name="xoa_nhom_hd"),

    path("ajax/lay-xa/", login_required(views.lay_danh_sach_xa), name="lay_danh_sach_xa"),

    path("hop-dong/import-phan-cong/", login_required(views.import_phan_cong), name="import_phan_cong"),
    path("hop-dong/phan-cong/", login_required(views.danh_sach_phan_cong), name="danh_sach_phan_cong"),
    path("hop-dong/phan-cong/them/", login_required(views.them_phan_cong), name="them_phan_cong"),
    path("hop-dong/phan-cong/sua/<int:pk>/", login_required(views.sua_phan_cong), name="sua_phan_cong"),
    path("hop-dong/phan-cong/xoa/<int:pk>/", login_required(views.xoa_phan_cong), name="xoa_phan_cong"),
    path("hop-dong/phan-cong/dieu-chuyen/<int:pk>/", login_required(views.dieu_chuyen_phan_cong), name="dieu_chuyen_phan_cong"),
    path("hop-dong/phan-cong/lich-su/<int:pk>/", login_required(views.lich_su_phan_cong), name="lich_su_phan_cong"),

    path("hop-dong/tao-moi/", login_required(views.phan_bo_chi_tieu), name="phan_bo_chi_tieu"),
    path("hop-dong/danh-sach-phan-bo/", login_required(views.danh_sach_phan_bo), name="danh_sach_phan_bo"),
    path("phan-bo/<int:pk>/xoa/", login_required(views.xoa_phan_bo), name="xoa_phan_bo"),
    path("hop-dong/import-phan-bo/", login_required(views.import_phan_bo), name="import_phan_bo"),
    path("hop-dong/import-phan-bo/confirm/", login_required(views.confirm_import_phan_bo), name="confirm_import_phan_bo"),
    path("phan-bo/<int:pk>/sua/", login_required(views.sua_phan_bo_chi_tieu), name="sua_phan_bo_chi_tieu"),
    path("phan-bo/<int:pk>/khoa/", login_required(views.khoa_phan_bo), name="khoa_phan_bo"),

    path("danh-sach-de-xuat/", login_required(views.danh_sach_de_xuat), name="danh_sach_de_xuat"),
    path("de-xuat/<int:pk>/tao/", login_required(views.tao_de_xuat_hop_dong), name="tao_de_xuat_hop_dong"),
    path("de-xuat/<int:pk>/duyet/", login_required(views.duyet_de_xuat), name="duyet_de_xuat"),

    path("hop-dong/tao-chinh-thuc/<int:pk>/", login_required(views.tao_hop_dong_chinh_thuc), name="tao_hop_dong_chinh_thuc"),
    path("hop-dong/", login_required(views.danh_sach_hop_dong), name="danh_sach_hop_dong"),
    path("hop-dong/import/", login_required(views.import_hop_dong), name="import_hop_dong"),
    path("hop-dong/<int:pk>/", login_required(views.chi_tiet_hop_dong), name="chi_tiet_hop_dong"),
    path("hop-dong/<int:pk>/sua/", login_required(views.sua_hop_dong), name="sua_hop_dong"),
    path("hop-dong/<int:pk>/xoa/", login_required(views.xoa_hop_dong), name="xoa_hop_dong"),
    path("hop-dong/<int:pk>/xuat-bo-hop-dong/", login_required(views.xuat_bo_hop_dong), name="xuat_bo_hop_dong"),
    path("hop-dong/<int:pk>/xuat-phu-luc-phan-cong/", login_required(views.xuat_phu_luc_phan_cong), name="xuat_phu_luc_phan_cong"),
    path("hop-dong/<int:hop_dong_id>/khoi-luong/them/", login_required(views.them_khoi_luong_hop_dong), name="them_khoi_luong_hop_dong"),
    path("hop-dong/<int:hop_dong_id>/phu-luc/them/", login_required(views.them_phu_luc_hop_dong), name="them_phu_luc_hop_dong"),
    path("hop-dong/<int:hop_dong_id>/nhat-ky/them/", login_required(views.them_nhat_ky_thuc_hien), name="them_nhat_ky_thuc_hien"),
    path("nhat-ky-can-thiep/them/", login_required(views.them_nhat_ky_can_thiep), name="them_nhat_ky_can_thiep"),
    path("nhat-ky-can-thiep/<int:pk>/sua/", login_required(views.sua_nhat_ky_can_thiep), name="sua_nhat_ky_can_thiep"),
    path("nhat-ky-can-thiep/<int:pk>/xoa/", login_required(views.xoa_nhat_ky_can_thiep), name="xoa_nhat_ky_can_thiep"),
    path("hop-dong/<int:hop_dong_id>/thanh-toan/them/", login_required(views.tao_dot_thanh_toan), name="tao_dot_thanh_toan"),
    path("thanh-toan/<int:pk>/", login_required(views.chi_tiet_dot_thanh_toan), name="chi_tiet_dot_thanh_toan"),
    path("thanh-toan/<int:pk>/xuat-de-nghi/", login_required(views.xuat_de_nghi_thanh_toan), name="xuat_de_nghi_thanh_toan"),
    path("thanh-toan/<int:pk>/xuat-danh-sach-tai-khoan/", login_required(views.xuat_danh_sach_tai_khoan), name="xuat_danh_sach_tai_khoan"),
    path("hop-dong/<int:hop_dong_id>/nghiem-thu/", login_required(views.cap_nhat_nghiem_thu), name="cap_nhat_nghiem_thu"),
    path("hop-dong/<int:hop_dong_id>/thanh-ly/", login_required(views.cap_nhat_thanh_ly), name="cap_nhat_thanh_ly"),
    path("hop-dong/<int:pk>/xuat-bien-ban-nghiem-thu/", login_required(views.xuat_bien_ban_nghiem_thu), name="xuat_bien_ban_nghiem_thu"),
    path("hop-dong/<int:pk>/xuat-bien-ban-thanh-ly/", login_required(views.xuat_bien_ban_thanh_ly), name="xuat_bien_ban_thanh_ly"),
    path("thanh-toan/<int:dot_id>/chi-tiet/them/", login_required(views.them_chi_tiet_thanh_toan), name="them_chi_tiet_thanh_toan"),
    path("hop-dong/<int:hop_dong_id>/thanh-toan-di-lai-phu-huynh/them/", login_required(views.tao_dot_thanh_toan_phu_huynh), name="tao_dot_thanh_toan_phu_huynh"),
    path("thanh-toan-di-lai-phu-huynh/<int:pk>/", login_required(views.chi_tiet_dot_thanh_toan_phu_huynh), name="chi_tiet_dot_thanh_toan_phu_huynh"),
    path("thanh-toan-di-lai-phu-huynh/<int:dot_id>/chi-tiet/them/", login_required(views.them_chi_tiet_thanh_toan_phu_huynh), name="them_chi_tiet_thanh_toan_phu_huynh"),
    path("thanh-toan-di-lai-phu-huynh/<int:pk>/xuat-dntt/", login_required(views.xuat_dntt_di_lai_phu_huynh), name="xuat_dntt_di_lai_phu_huynh"),
    path("thanh-toan-di-lai-phu-huynh/<int:pk>/xuat-dstk/", login_required(views.xuat_dstk_di_lai_phu_huynh), name="xuat_dstk_di_lai_phu_huynh"),
    path("nhat-ky-can-thiep/", login_required(views.nhat_ky_can_thiep), name="nhat_ky_can_thiep"),
    path("nhat-ky-can-thiep/import/", login_required(views.import_nhat_ky_can_thiep), name="import_nhat_ky_can_thiep"),
    path("thanh-quyet-toan/", login_required(views.thanh_quyet_toan), name="thanh_quyet_toan"),
    path("de-nghi-thanh-toan/", login_required(views.de_nghi_thanh_toan), name="de_nghi_thanh_toan"),
    path("nhat-ky-can-thiep/xuat-dntt/", login_required(views.xuat_dntt_nhat_ky), name="xuat_dntt_nhat_ky"),
    path("nhat-ky-can-thiep/xuat-dntt-excel/", login_required(views.xuat_dntt_excel_nhat_ky), name="xuat_dntt_excel_nhat_ky"),
    path("nhat-ky-can-thiep/xuat-dstk/", login_required(views.xuat_dstk_nhat_ky), name="xuat_dstk_nhat_ky"),
    path("nhat-ky-can-thiep/xuat-dnck/", login_required(views.xuat_dnck_nhat_ky), name="xuat_dnck_nhat_ky"),
]
